- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - usct

- name: Clone Sandbox Backend Deployment Repo
  ansible.builtin.git:
    repo: https://github.com/oci-sunbird/sandbox-usecase-usct-backend.git
    dest: /root/govstack/usct_backend
    single_branch: yes
    version: customized_backend

