
- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /root/govstack/customization

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - usct

- name: Clone Sandbox Backend Deployment Repo
  ansible.builtin.git:
    repo: https://github.com/GovStackWorkingGroup/sandbox-usecase-usct-backend.git
    dest: /root/govstack/customization
    single_branch: yes
    version: main

