- name: Uninstall USCT
  shell: |
    helm uninstall usct --namespace sandbox-im
    sleep 60
    for pvc in $(kubectl -n sandbox-im get pvc -o name); do
      kubectl -n sandbox-im delete $pvc
    done


