usct_namespace: usct
usct_prefix: sandbox

backend_enabled: true
frontend_enabled: true
open_imis_enabled: false
im_enabled: true
consent_enabled: false
payment_hub_enabled: false
payment_emulator_enabled: true
digital_registries_emulator_enabled: true


backend_image: ghcr.io/govstackworkinggroup/sandbox-usecase-usct-backend
backend_image_tag: paymenthub-1
backend_auth_mode: local
backend_payment_mode: emulator
backend_payment_base_url: http://sandbox-xroad-ss2.sandbox-im.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/PAYMENT/api
backend_payment_hub_acc_map_url: http://sandbox-xroad-ss2.sandbox-im.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/PAYMENT/account-mapper
backend_payment_hub_bulk_conn_url: http://sandbox-xroad-ss2.sandbox-im.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/PAYMENT/bulk-connector
backend_payment_hub_callback_url: http://backend.usct.svc.cluster.local:8080
backend_open_ims_url: http://sandbox-xroad-ss2.sandbox-im.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/DIGITAL-REGISTRIES/api/data/registryname/111?search=package&filter=phone
backend_open_ims_emulator_url: http://sandbox-xroad-ss2.sandbox-im.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/DIGITAL-REGISTRIES/emulator/api/v1/data/bpkg/1.0
backend_consent_url: http://sandbox-xroad-ss2.sandbox-im.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/CONSENT/api/v2/service/individual/record/

open_imis_deployment_password: Welc@me1234
open_imis_postgress_password: Welc@me1234

frontend_image: ghcr.io/govstackworkinggroup/sandbox-usecase-usct-frontend:latest

consent_smtp_admin_email: xyz@gmail.com
consent_smtp_user_email: xyz@gmail.com

demo_password: Welc@me1234